services:
  web:
    build: .
    ports:
      - "3001:8000"
    depends_on:
      - redis
      - mongo
  redis:
    image: "redis:latest"
    ports: 
      - "6379:6379"
  mongo:
    image: "mongo:latest"